// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrwe5NVEOsYFxESvpy40UzmbU_PCBYiqk',
    appId: '1:717759817966:web:19aeb0c5bd3a03e2fb6bff',
    messagingSenderId: '717759817966',
    projectId: 'instergramclone-fa9af',
    authDomain: 'instergramclone-fa9af.firebaseapp.com',
    storageBucket: 'instergramclone-fa9af.appspot.com',
    measurementId: 'G-183QRHWSX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhbgh6nA-LXhE-WMIMcyKCIFTmFfrdh0',
    appId: '1:717759817966:android:0b73fef8304989c9fb6bff',
    messagingSenderId: '717759817966',
    projectId: 'instergramclone-fa9af',
    storageBucket: 'instergramclone-fa9af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxabaE08L3bk2qRikA2fDUDRQEW1yN-8I',
    appId: '1:717759817966:ios:c3bcccc9a46504e8fb6bff',
    messagingSenderId: '717759817966',
    projectId: 'instergramclone-fa9af',
    storageBucket: 'instergramclone-fa9af.appspot.com',
    iosBundleId: 'com.example.instergramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxabaE08L3bk2qRikA2fDUDRQEW1yN-8I',
    appId: '1:717759817966:ios:a16dedc20e49c00efb6bff',
    messagingSenderId: '717759817966',
    projectId: 'instergramclone-fa9af',
    storageBucket: 'instergramclone-fa9af.appspot.com',
    iosBundleId: 'com.example.instergramClone.RunnerTests',
  );
}
